//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServiceManagementEntities : DbContext
    {
        public ServiceManagementEntities()
            : base("name=ServiceManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblMechanic> tblMechanics { get; set; }
        public virtual DbSet<tblService> tblServices { get; set; }
        public virtual DbSet<tblUserRegistration> tblUserRegistrations { get; set; }
        public virtual DbSet<tblVehicalCompany> tblVehicalCompanies { get; set; }
        public virtual DbSet<tblVehicalDetail> tblVehicalDetails { get; set; }
        public virtual DbSet<tblVehicalName> tblVehicalNames { get; set; }
        public virtual DbSet<tblVehicalType> tblVehicalTypes { get; set; }
        public virtual DbSet<Usertype> Usertypes { get; set; }
    }
}
