//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVehicalName
    {
        public string Id { get; set; }
        public Nullable<int> VehicalCompanyId { get; set; }
        public string VehicalName { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual tblVehicalCompany tblVehicalCompany { get; set; }
    }
}
