//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVehicalDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVehicalDetail()
        {
            this.tblServices = new HashSet<tblService>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Userid { get; set; }
        public Nullable<int> VehicalTypeId { get; set; }
        public Nullable<int> VehicalCompanyId { get; set; }
        public string VehicalName { get; set; }
        public string OwnerName { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string ChassisNo { get; set; }
        public string LicencePlateNo { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblService> tblServices { get; set; }
        public virtual tblUserRegistration tblUserRegistration { get; set; }
        public virtual tblVehicalCompany tblVehicalCompany { get; set; }
        public virtual tblVehicalType tblVehicalType { get; set; }
    }
}
